# Generated by Django 2.1.3 on 2019-01-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentGroup',
        ),
    ]
