# Generated by Django 2.1.3 on 2019-01-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190129_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Group'),
        ),
    ]
